---
title:  "CTE Trailblazers data preparations"
author: "Arthur Small"
date:   "Version of `r Sys.Date()`"
output:
  html_notebook: default
  pdf_document: default
editor_options:
  chunk_output_type: inline
---

# Introduction

In the beginning...



```{r page setup, include=FALSE}

```

```{r new example chunk, include=FALSE}
num_observations <- 2*5*4
```

Our study employed `r num_observations` observations.


```{r load packages, include=FALSE}
library(tidyverse)
library(readxl)
```

```{r read in data, include=FALSE}
local_root_dir <- "/Users/Arthur/OneDrive - University of Virginia/"
data_dir       <- "Documents/Projections/2018-28/Data/Store/"
file_name      <- "Projections_2018-28_PRIME_2021-05-20.xlsx"
 
path2file <- paste0(local_root_dir,data_dir,file_name)

file_name      <- "Projections_2018-28_PRIME_2021-05-20.xlsx"

readxl::read_xlsx(path=file_name, sheet = "SOC Summary")
readxl::read_xlsx(path=file_name, sheet = "Nonduplicated")
readxl::read_xlsx(path=file_name, sheet = "Duplicated")
```

```{r clean data}
readxl::read_xlsx(path=file_name, sheet = "SOC Summary")[1,3] %>% pull() -> na_symbol

readxl::read_xlsx(path=file_name, 
                  sheet = "SOC Summary",
                  col_types = c("skip", "skip", "text", "text", "text", rep("numeric",7)),
                  na = na_symbol) -> soc_summary


fix_names <- function(x){
  x <- str_replace_all(string = x, pattern = "[ -]", replacement = "_")
  x <- str_to_lower(x)
  x <- str_remove_all(x, pattern = "2018_")
  x <- str_remove_all(x, pattern = "2028_")
  x <- str_remove_all(x, pattern = "28_")
  
  return(x)
}

soc_summary %>%
  rename_with(.fn = fix_names) %>%
  rename(fraction_change = percent_change) %>%
  mutate(occ_group_type = as.factor(occ_group_type),
         annual_growth_rate = (log(projection)-log(estimate))/10) -> soc_summary_tbl

soc_summary_tbl

readxl::read_xlsx(path=file_name, sheet = "Nonduplicated")[1,21] %>% pull() -> na_symbol

readxl::read_xlsx(path=file_name, 
                  sheet = "Nonduplicated",
                  col_types = c(rep("text", 13), rep("numeric",8)),
                  na = na_symbol) -> nonduplicated_summary

nonduplicated_summary <- nonduplicated_summary %>%
  rename_with(.fn = fix_names) %>% 
  rename(fraction_change = percent_change) %>%
  rename(fraction_change_us = percent_change_us)

readxl::read_xlsx(path=file_name, sheet = "Duplicated")[1,21] %>% pull() -> na_symbol

readxl::read_xlsx(path=file_name, 
                  sheet = "Duplicated",
                  col_types = c(rep("text", 13), rep("numeric",8)),
                  na = na_symbol) -> duplicated_summary

duplicated_summary <- duplicated_summary %>%
  rename_with(.fn = fix_names) %>% 
  rename(fraction_change = percent_change) %>%
  rename(fraction_change_us = percent_change_us)

```

```{r display data for management occupations}

soc_summary_tbl %>%
  filter(str_starts(soc_code, pattern = "11")) %>%
  filter(soc_title != "Management Occupations") %>%
  select(soc_code:annual_openings) -> df

df %>%
  ggplot(aes(x = soc_code, y=estimate)) + geom_col()

```
```{r}
ggsave(here::here("images", "box-plot.png"))
```
```{r visualizing growth}

ggplot(nonduplicated_summary %>% filter(cluster == "Agriculture, Food, and Natural Resources"), aes(pathway, fill = predominant_education_level)) + geom_bar() + theme(axis.text.x=element_text(angle = 45, h = 1))

```
```{r labor market analysis, include = TRUE}

non_duplicated_by_labor_market <- nonduplicated_summary %>% 
  select(cluster, pathway, soc_title, estimate, annual_openings, projection, fraction_change) %>%  
  group_by(cluster)

non_duplicated_by_labor_market

ggplot(non_duplicated_by_labor_market, aes(log10(estimate), log10(projection))) + geom_point() + facet_wrap(~cluster)
cor.test(non_duplicated_by_labor_market$projection, non_duplicated_by_labor_market$estimate)
```
Above graphs show a roughly linear correlation between the estimate for number of jobs available by cluster now and the number projected in 10 years. 

```{r growth rates, incude = TRUE}
ggplot(non_duplicated_by_labor_market, aes(cluster,fraction_change)) + 
  geom_line() + 
  theme(axis.text.x=element_text(angle = 90, h = 1))

cluster_averages <- non_duplicated_by_labor_market %>% summarize(cluster_change = mean(fraction_change), cluster_min = min(fraction_change), cluster_max = max(fraction_change))
cluster_averages

ggplot(cluster_averages, aes(cluster, cluster_change)) + 
  geom_point() + 
  theme(axis.text.x = element_text(angle = 90, h = 1)) + 
  geom_errorbar(aes(ymax = cluster_max, ymin = cluster_min, width = 0.1), color = "grey")

ggplot(non_duplicated_by_labor_market, aes(pathway, fraction_change, color = cluster)) + geom_point() 

ggplot(non_duplicated_by_labor_market %>% filter(cluster == "Agriculture, Food, and Natural Resources"), 
       aes(pathway, fraction_change)) + geom_point() + 
  theme(axis.text.x=element_text(angle = 90, h = 1))

ggplot(non_duplicated_by_labor_market %>% filter(cluster == "Architecture and Construction"), 
       aes(pathway, fraction_change)) + geom_point() + 
  theme(axis.text.x=element_text(angle = 90, h = 1))
 
ggplot(non_duplicated_by_labor_market %>% filter(cluster == "Arts, Audio/Video Technology, and Communications"), 
       aes(pathway, fraction_change)) + geom_point() + 
  theme(axis.text.x=element_text(angle = 90, h = 1)) 

ggplot(non_duplicated_by_labor_market %>% filter(cluster == "Business Management and Administration"), 
       aes(pathway, fraction_change)) + geom_point() + 
  theme(axis.text.x=element_text(angle = 90, h = 1))

ggplot(non_duplicated_by_labor_market %>% filter(cluster == "Education and Training"), 
       aes(pathway, fraction_change)) + geom_point() + 
  theme(axis.text.x=element_text(angle = 90, h = 1))

ggplot(non_duplicated_by_labor_market %>% filter(cluster == "Energy"), 
       aes(pathway, fraction_change)) + geom_point() + 
  theme(axis.text.x=element_text(angle = 90, h = 1))

ggplot(non_duplicated_by_labor_market %>% filter(cluster == "Finance"), 
       aes(pathway, fraction_change)) + geom_point() + 
  theme(axis.text.x=element_text(angle = 90, h = 1))

ggplot(non_duplicated_by_labor_market %>% filter(cluster == "Government and Public Administration"), 
       aes(pathway, fraction_change)) + geom_point() + 
  theme(axis.text.x=element_text(angle = 90, h = 1))

ggplot(non_duplicated_by_labor_market %>% filter(cluster == "Health Science"), 
       aes(pathway, fraction_change)) + geom_point() + 
  theme(axis.text.x=element_text(angle = 90, h = 1))

ggplot(non_duplicated_by_labor_market %>% filter(cluster == "Hospitality and Tourism"), 
       aes(pathway, fraction_change)) + geom_point() + 
  theme(axis.text.x=element_text(angle = 90, h = 1))

ggplot(non_duplicated_by_labor_market %>% filter(cluster == "Human Services"), 
       aes(pathway, fraction_change)) + geom_point() + 
  theme(axis.text.x=element_text(angle = 90, h = 1))

ggplot(non_duplicated_by_labor_market %>% filter(cluster == "Information Technology"), 
       aes(pathway, fraction_change)) + geom_point() + 
  theme(axis.text.x=element_text(angle = 90, h = 1))

ggplot(non_duplicated_by_labor_market %>% filter(cluster == "Science, Technology, Engineering, and Mathematics"), 
       aes(pathway, fraction_change)) + geom_point() + 
  theme(axis.text.x=element_text(angle = 90, h = 1))

ggplot(non_duplicated_by_labor_market %>% filter(cluster == "Transportation, Distribution, and Logistics"), 
       aes(pathway, fraction_change)) + geom_point() + 
  theme(axis.text.x=element_text(angle = 90, h = 1))
```

