library(tidyverse)

Ag_text <- c('This analysis of Virginia\'s Agriculture, Food, and Natural Resources cluster highlights important information about each of its seven career pathways - Food Products and Processing Systems; Plant Systems; Animal Systems; Power, Structural, and Technical Systems;  Natural Resources Systems; Environmental Service Systems; and Agribusiness Systems.',
             "The 4.0 percent growth projected for the Agriculture, Food, and Natural Resources cluster from 2018 to 2028 is less than the 6.6 percent average growth expected for all occupations in Virginia.",
             "There were slightly fewer than 76,500 jobs classified in Virginia\'s Agriculture, Food, and Natural Resources cluster in 2018. Over 3,000 new jobs are projected to be created within the cluster by 2028, and about 8,800 job openings are expected throughout Virginia annually.",
             "The Animal Systems pathway, consisting of three veterinary occupations, is projected to expand by a greater percentage 33.0% than any other pathway in any cluster through the year 2028. Two of these veterinary occupations - Veterinary Technologists and Technicians; and Veterinary Assistants and Laboratory Animal Caretakers - are expected to grow by about 34 percent through 2028, placing them among the top five fastest-growing occupations in Virginia.",
             "In addition to the Animal Systems pathway, the Plant Systems pathway is projected to have slightly higher-than-average job growth through 2028 (6.7%).")

Arc_text <- c('This analysis of Virginia\'s Architecture & Construction cluster highlights important information about each of its three career pathways - Design/Pre-Construction; Construction; and Maintenance/Operations.',
              "The 9.1 percent job growth projected for the Architecture & Construction cluster from 2018 to 2028 is greater than the 6.6 percent average growth expected for all occupations in Virginia.",
              "There were slightly fewer than 378,500 jobs classified in the commonwealth\'s Architecture & Construction cluster in 2018. Approximately 34,300 new jobs are projected to be created within the cluster by 2028, and about 47,600 job openings are expected throughout Virginia annually.",
              "All three pathways in the Architecture & Construction cluster are projected to experience higher-than-average growth rates through 2028.",
              "A high school diploma is the predominant education level of 93 percent of occupations in the Construction pathway and 71 percent of occupations in the Maintenance/Operations pathway. All occupations in the Design/Pre-Construction pathway, however, have a predominant education level greater than a high school diploma.",
              "Among occupations with a predominant education level of high school diploma, two of the three highest-paying are in the Construction pathway - First-Line Supervisors of Construction Trades and Extraction Workers; and Crane and Tower Operators - with Virginia 2018 median annual incomes of $64,614 and $63,244, respectively.")

Arts_text <- c('This analysis of Virginia\'s Arts, Audio/Video Technology, and Communications cluster highlights important information about each of its six career pathways - Audio/Video Technology and Film; Printing Technology; Visual Arts; Performing Arts; Journalism and Broadcasting; and Telecommunications.',
               "The 2.1 percent job growth projected for the Arts, Audio/Video Technology, and Communications cluster from 2018 to 2028 is less than the 6.6 percent average growth expected for all occupations in Virginia.",
               "There were slightly fewer than 57,500 Virginia jobs classified in the Arts, Audio/Video Technology, and Communications cluster in 2018. Approximately 1,200 new jobs are projected to be created within the cluster by 2028, and about 6,400 job openings are expected throughout Virginia each year.",
               "Two pathways in the Arts, Audio/Video Technology, and Communications cluster are projected to experience higher-than-average percentages of job growth through 2028 - Audio/Video Technology and Film (6.9%) and Telecommunications (10.8%). The Printing Technology pathway, however, will most likely continue to experience significant job decline (-15.3%) as a result of society's shift to digital publications.",
               "Choreographers in the Performing Arts pathway are one of the top five highest-paying occupations among those having a predominant education level of high school diploma, with a Virginia 2018 median annual income of $61,167")

Bus_text <- c('This analysis of Virginia\'s Business Management and Administration cluster highlights important information about each of its five career pathways - General Management; Business Information Management; Human Resources Management; Operations Management; and Administrative Support.',
              "The 3.6 percent job growth projected for the Business Management and Administration cluster from 2018 to 2028 is less than the 6.6 percent average growth expected for all occupations in Virginia.",
              "There were about 591,800 jobs classified in the Business Management and Administration cluster in 2018, making it the largest of all of Virginia\'s career clusters. Over 21,200 new jobs are projected to be created within the cluster by 2028, and nearly 65,800 job openings are expected throughout the commonwealth annually.",
              "Three pathways in the Business Management and Administration cluster are projected to experience a percentage of job growth greater than the state average of 6.6 percent - Business Information Management (14.4%); Operations Management (12.5%); and Human Resources Management (7.6%). The Administrative Support pathway, however, is expected to consist of about 5,200 (1.7%) fewer jobs in 2028 than in 2018.",
              "Among all occupations in Virginia having a predominant education level of bachelor\'s degree, Computer and Information Systems Managers in the Business Information Management pathway have the highest median annual income - $167,381 in 2018.")

Edu_text <- c('This analysis of Virginia\'s Education and Training cluster highlights important information about each of its three career pathways – Administration and Administrative Support; Professional Support Services; and Teaching/Training.',
              'The 4.6 percent job growth projected for the Education and Training cluster from 2018 to 2028 is less than the 6.6 percent average growth expected for all occupations in Virginia.',
              'There were slightly more than 218,800 jobs classified in the commonwealth’s Education and Training cluster in 2018. Over 10,000 new jobs are projected to be created within the cluster by 2028, and about 20,800 job openings are expected each year throughout Virginia.',
              'The largest pathway in this cluster, by far, is the Teaching/Training pathway, which is estimated to have provided over 182,000 jobs throughout Virginia in 2018. Despite lower-than-average projected job growth through 2028 (4.2%), nearly 17,000 job openings will be available in this pathway each year throughout the commonwealth.',
              'Only one pathway in the Education and Training cluster – Professional Support Services – is projected to have greater-than-average occupational growth through 2028 (7.1%). Within this pathway, Interpreters and Translators are expected to see an especially strong percentage of job growth in Virginia (18.1%).')

Energy_text <- c('This analysis of Virginia\'s Energy cluster highlights important information about each of its four career pathways - Fuels Production; Power Generation; Energy Transmission, Distribution, and Storage; and Energy Sustainability and Efficiency.',
                 'The 3.9 percent job growth projected for the Energy cluster from 2018 to 2028 is less than the 6.6 percent average growth expected for all occupations in Virginia.',
                 'Virginia\'s newest career cluster is also its smallest. There were about 12,400 jobs classified in the Energy cluster in 2018. Approximately 500 new jobs are projected to be created within the cluster by 2028, and about 1,200 job openings are expected throughout Virginia annually.',
                 'The Energy Transmission, Distribution, and Storage pathway is the only pathway in the Energy cluster expected to see above-average job growth (8.1%) through 2028, adding more than 450 new jobs throughout the state. The Fuels Production pathway, on the other hand, is likely to consist of about 80 fewer jobs by 2028, representing a decline of 6.8 percent.')

Fin_text <- c('This analysis of Virginia\'s Finance cluster highlights important information about each of its five career pathways - Securities and Investments; Business Finance; Accounting; Insurance; and Banking Services.',
              '5.6 percent job growth projected for the Finance cluster from 2018 to 2028 is slightly less than the 6.6 percent average growth expected for all occupations in Virginia.',
              'There were slightly fewer than 217,500 jobs classified in Virginia\'s Finance cluster in 2018. Almost 12,300 new jobs are projected to be created within the cluster by 2028, and nearly 23,200 job openings will likely be available in this cluster each year throughout the commonwealth.',
              'Two pathways in the Finance cluster are expected to experience above-average growth through 2028 - Securities and Investments (7.6%) and Business Finance (12.2%).',
              'Although the Accounting pathway is the largest of all pathways in Virginia’s Finance cluster, consisting of about 101,500 jobs in 2018, it is projected to experience the lowest percentage of job growth (3.0%) of all pathways within the cluster. Despite this slower growth rate, the Accounting pathway will still provide the most annual job openings (11,111) of any pathway in the cluster.')

Gov_text <- c('This analysis of Virginia\'s Government and Public Administration cluster highlights important information about six of its seven career pathways - Governance; National Security; Planning; Revenue and Taxation; Regulation; and Public Management and Administration. Virginia\'s Foreign Service pathway currently has no occupations assigned to it.',
              'The 5.5 percent job growth projected for the Government and Public Administration cluster from 2018 to 2028 is slightly less than the 6.6 percent average growth expected for all occupations in Virginia. In 2018, there were slightly more than 27,600 jobs classified exclusively in the Government and Public Administration cluster. About 1,500 new jobs are projected to be created within the cluster by 2028, and roughly 2,700 job openings will likely occur throughout Virginia in this cluster each year.',
              'Because occupations can only be assigned to one cluster to avoid double-counting jobs in the projections, and because many of the occupations that might have been included in this cluster are instead assigned to other clusters based on the nature of the work performed rather than the type of organization for which the work is performed, the Government and Public Administration cluster is Virginia’s second smallest in size. It is important to understand, however, that many of the workers in other clusters are actually government employees.',
              'Among all occupations in the Government and Public Administration cluster, Urban and Regional Planners are projected to experience the greatest percentage of job growth (11.2%), with more than 150 new jobs in this field expected throughout Virginia by 2028.')

Health_text <- c('This analysis of Virginia\'s Health Science cluster highlights important information about each of its five career pathways - Therapeutic Services; Diagnostic Services; Health Informatics; Support Services; and Biotechnology Research and Development.',
                 'The 14.6 percent job growth projected for the Health Science cluster from 2018 to 2028 is much greater than the 6.6 percent average growth expected for all occupations in Virginia.',
                 'There were just over 307,800 jobs classified in Virginia\'s Health Science cluster in 2018. Roughly 45,000 new jobs are projected to be created within the cluster by 2028, and about 29,600 jobs are expected to open up annually in this cluster in Virginia.',
                 'All five pathways in the Health Science cluster are expected to experience higher-than-average job growth rates from 2018 to 2028.',
                 'Nearly half (48%) of the top 50 occupations in Virginia in terms of projected percentage of job growth between 2018 and 2028 are in the Health Science cluster.',
                 'Occupations with strong forecasted job growth exist at all education levels within the Health Science cluster - from Physician Assistants (32.6%) and Nurse Practitioners (30.8%) at the graduate/professional degree level to Phlebotomists (35.0%) and Occupational Therapy Assistants (33.5%) at the associate degree level to Home Health Aides (32.1%) at the high school diploma level.')

Tour_text <- c('This analysis of Virginia\'s Hospitality and Tourism cluster highlights important information about each of its four career pathways - Restaurants and Food/Beverage Services; Lodging; Travel and Tourism; and Recreation, Amusements, and Attractions.',
               'The 10.4 percent job growth projected for the Hospitality and Tourism cluster from 2018 to 2028 is greater than the 6.6 percent average growth expected for all occupations in Virginia.',
               'There were more than 409,500 jobs classified in Virginia\'s Hospitality and Tourism cluster in 2018. Over 42,600 new jobs are projected to be created within this cluster by 2028, and more than 76,500 job openings are expected annually in Virginia, the most of any cluster.',
               'The Restaurants and Food/Beverage Services pathway is the second largest career pathway in Virginia, consisting of an estimated 343,327 jobs in 2018 and accounting for about 84 percent of all jobs in the Hospitality and Tourism cluster.',
               'Two of the four pathways in this cluster are projected to have greater-than-average job growth through 2028 - Restaurants and Food/Beverage Services (11.8%) and Recreation, Amusements, and Attractions (8.4%).')

Hum_text <- c('This analysis of Virginia\'s Human Services cluster highlights important information about each of its five career pathways - Early Childhood Development and Services; Counseling and Mental Health Services; Family and Community Services; Personal Care Services; and Consumer Services.',
              'The 18.1 percent job growth projected for the Human Services cluster from 2018 to 2028 - second highest among all clusters - is much greater than the 6.6 percent average growth expected for all occupations in Virginia.',
              'There were about 166,700 jobs classified in Virginia\'s Human Services cluster in 2018. Roughly 30,300 new jobs are projected to be created within this cluster by 2028, and slightly fewer than 26,400 job openings are expected each year in Virginia.',
              'All pathways in the Human Services cluster except Early Childhood Development and Services are expected to experience job growth greater than the state average for all occupations.',
              'The Personal Care Services pathway is the largest pathway in the Human Services cluster and the most diverse in terms of the predominant education level of its occupations. It is expected to expand by 24.0 percent from 2018 to 2028 - the second-highest percentage of growth among all career pathways in Virginia.',
              'Personal Care Aides in the Personal Care Services pathway are projected to see job growth of 36.9 percent through 2028 - the second-highest percentage of growth among all occupations in Virginia.')

IT_text <- c('This analysis of Virginia\'s Information Technology cluster highlights important information about each of its four career pathways - Network Systems; Information Support and Services; Web and Digital Communications; and Programming and Software Development.',
             'The 19.3 percent job growth projected for the Information Technology cluster from 2018 to 2028 is much greater than the 6.6 percent average growth expected for all occupations in Virginia and is the highest projected percentage of growth among all career clusters.',
             'There were slightly fewer than 201,800 jobs classified in Virginia\'s Information Technology cluster in 2018. Roughly 39,000 new jobs are projected to be created within the cluster by 2028, and about 20,000 job openings are expected throughout Virginia annually.',
             'All four pathways in the Information Technology cluster are projected to sustain occupational growth of 12 percent or greater between 2018 and 2028.',
             'Information Security Analysts in the Network Systems pathway are projected to have the highest percentage of job growth of any occupation in Virginia (45.4%), with more than 6,600 new jobs in this occupation expected in Virginia by 2028.')

Law_text <- c('This analysis of Virginia\'s Law, Public Safety, Corrections, and Security cluster highlights important information about each of its five career pathways - Correction Services; Emergency and Fire Management Services; Security and Protective Services; Law Enforcement Services; and Legal Services.',
              'The 2.1 percent job growth projected for the Law, Public Safety, Corrections, and Security cluster from 2018 to 2028 is less than the 6.6 percent average growth expected for all occupations in Virginia.',
              'There were slightly more than 149,000 jobs classified in Virginia\'s Law, Public Safety, Corrections, and Security cluster in 2018. Just over 3,200 new jobs are projected to be created within the cluster by 2028, and approximately 13,800 job openings are expected throughout Virginia annually.',
              'Emergency and Fire Management Services is the only pathway in this cluster projected to grow by a greater percentage than average through 2028 (7.5%).',
              'About two thirds (67%) of occupations in the Law, Public Safety, Corrections, and Security cluster have a predominant education level of some college / associate degree.',
              'The two occupations in the Law, Public Safety, Corrections, and Security cluster with the greatest projected proportions of either job growth or decline between 2018 and 2028 are in the Legal Services pathway. Court Reporters are expected to see 16.1 percent job growth, while Legal Secretaries will most likely experience job decline of 27.9 percent.')

Manuf_text <- c('This analysis of Virginia\'s Manufacturing cluster highlights important information about each of its six career pathways - Production; Manufacturing Production Process Development; Maintenance, Installation, and Repair; Quality Assurance; Logistics and Inventory Control; and Health, Safety, and Environmental Assurance.',
                'The Manufacturing cluster in Virginia is expected to have 0.9 percent fewer jobs available in 2028 compared to 2018, making it the only career cluster in Virginia projected to experience job contraction.',
                'There were approximately 179,200 jobs classified in Virginia\'s Manufacturing cluster in 2018. About 1,600 fewer jobs are projected to exist within the cluster by 2028; however, approximately 19,400 job openings are expected annually within Virginia.',
                'The Production pathway is by far the largest in the Manufacturing cluster, consisting of about 96,000 jobs in 2018 - a little more than half (54%) of all jobs in the Manufacturing cluster.',
                'Five occupations in Virginia\'s Manufacturing cluster are expected to experience job growth of 10 percent or more through 2028 - Computer Numerically Controlled Machine Tool Programmers, Metal and Plastic (19.5%); Ophthalmic Laboratory Technicians (15.0%); Etchers and Engravers (11.1%); Medical Appliance Technicians (10.9%); and Dental Laboratory Technicians (10.1%).')

Mark_text <- c('This analysis of Virginia\'s Marketing cluster highlights important information about each of its five career pathways - Marketing Management; Professional Sales; Merchandising; Marketing Communications; and Marketing Research.',
               'The 1.4 percent job growth projected for the Marketing cluster from 2018 to 2028 is less than the 6.6 percent average growth expected for all occupations in Virginia.',
               'There were around 514,500 jobs classified in the Marketing cluster in 2018, making it the second largest of Virginia\'s career clusters. Roughly 7,300 new jobs are projected to be created within the cluster by 2028, and more than 72,300 job openings are expected throughout the commonwealth annually.',
               'Three pathways in the Marketing cluster are expected to have higher-than-average rates of growth through 2028 - Marketing Management (8.2%), Marketing Communications (8.7%), and Marketing Research (21.8%).',
               'The projected percentage of job growth for the Marketing Research pathway (21.8%) is the fourth highest among all career pathways in Virginia.',
               'Professional Sales is the largest pathway in Virginia, consisting of over 415,400 jobs in 2018. It is also the only pathway in the Marketing cluster that is projected to contract in size slightly (-0.2%), with a loss of about 870 jobs expected by 2028.')

STEM_text <- c('This analysis of Virginia\'s Science, Technology, Engineering, and Mathematics (STEM) cluster highlights important information about each of its two career pathways - Engineering and Technology; and Science and Mathematics.',
               'The 7.6 percent job growth projected for the STEM cluster from 2018 to 2028 is slightly greater than the 6.6 percent average growth expected for all occupations in Virginia.',
               'There were slightly fewer than 64,500 jobs classified in the commonwealth\'s STEM cluster in 2018. Nearly 5,000 new jobs are projected to be created within the cluster by 2028, and around 5,800 job openings are expected annually throughout Virginia.',
               'Both pathways in the STEM cluster are projected to expand by greater percentages than the state average - Engineering and Technology by 7.0 percent and Science and Mathematics by 8.8 percent.',
               'All occupations in the STEM cluster have a predominant education level greater than a high school diploma - 8 percent have an education level of some college /associate degree; 47 percent, bachelor\'s degree; and 45 percent, graduate or professional degree.',
               'In 2018, all occupations in the STEM cluster had a median annual income higher than the state median of $41,741. The only other cluster for which this is true is Information Technology.')

Transp_text <- c("This analysis of Virginia\'s Transportation, Distribution, and Logistics cluster highlights important information about six of its seven career pathways - Transportation Operations; Logistics Planning and Management Services; Warehousing and Distribution Center Operations; Facility and Mobile Equipment Maintenance;  Transportation Systems / Infrastructure Planning, Management, and Regulation; and Sales and Service. Virginia\'s Health, Safety, and Environmental Management pathway currently has no occupations assigned to it.",
                 'The 3.1 percent job growth projected for the Transportation, Distribution, and Logistics cluster from 2018 to 2028 is less than the 6.6 percent average growth expected for all occupations in Virginia.',
                 'In 2018, there were slightly more than 298,400 jobs classified in Virginia\'s Transportation, Distribution, and Logistics cluster. Slightly fewer than 9,200 new jobs are projected to be created within the cluster by 2028, and roughly 35,600 job openings are expected each year throughout Virginia.',
                 'All career pathways in this cluster are expected to see positive job growth through 2028 except for Sales and Service, which is projected to experience job contraction of 2.8 percent.')


