---
title: "CTE Trailblazers: Regional Analysis"
author: "Arthur Small"
date:    Version of `r Sys.Date()`
output:  html_notebook
editor_options: 
  chunk_output_type: inline
---
 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r importing spreadsheet & packages, making edits for ease of graphing, warning = FALSE, message = FALSE, echo=FALSE}
library(dplyr)
library(stringr)

source(here::here("r", "read_trailblazers_xlsx_file.R"))  # define function read_1_xlsx() for reading in and parsing trailblazers data files

regional_data_dir   <- here::here("data_raw","Regional")
statewide_data_file <- here::here("data_raw","Projections_2018-28_PRIME_2021-05-20.xlsx")

fs::dir_ls(regional_data_dir, recurse = FALSE)  %>%
  str_subset(pattern = ".xlsx") %>% 
  append(statewide_data_file) %>% 
  purrr::map_dfr(read_1_xlsx) %>%
  
  
  filter(is.na(pathway_code)) %>%
  select(cluster_code, cluster, area, fraction_change) %>%
  arrange(cluster, desc(fraction_change), area) -> regional_tbl

# split_LWDA_text <- function(area_char_vec){
#   # Split the LWDA "area" text field into three pieces: name, type, area code
#   require(stringr)
#   
#   split1 <- str_split(area_char_vec, fixed(" ("), simplify = TRUE)
#   split2 <- str_remove(split1[,2],   fixed(")"))
#   split3 <- str_split(split2, " ", simplify = TRUE)
#   
#   return(cbind(split1[,1], split3))
# }

regional_tbl %>% 
  group_by(cluster_code) %>%
  filter(fraction_change > fraction_change[which(area == "Virginia")]) %>%
  ungroup() %>%
  select(-cluster_code) %>%
  mutate(Projected_Growth_Rate = scales::percent(fraction_change, accuracy = 0.1L)) %>%
  select(Cluster = cluster, Region, LWDA, Projected_Growth_Rate) -> growing_regions_tbl
```

```{r print table of regional growth rates}
print(growing_regions_tbl)
```

```{r save tibble of regional growth rates, echo=FALSE}
save2file <- here::here("regions", "growing_regions_tbl.Rds")
saveRDS(growing_regions_tbl, save2file)
```

