---
title: "Make Cluster Briefs Graphs"
author: "Abigail Freed and Arthur Small"
date:    Version of `r Sys.Date()`
output:  html_notebook
editor_options: 
  chunk_output_type: inline
---
 
```{r setup knitr, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r set up data and lists and prepare lists, warning = FALSE, message = FALSE}
library(tidyverse)
library(reshape2)
library(scales)
library(GGally)
library(ggfittext)

# Read in prepared data; filter to only statewide data
readRDS(here::here("data_prep","nonduplicated-all-regions-and-pathways.Rds")) %>%
  filter(region == "Virginia")  -> nonduplicated_prepped

# Extract vector of cluster names
cluster_names_vec <- unique(nonduplicated_prepped$cluster, fromLast = TRUE) 
cluster_names_vec <- cluster_names_vec[which(cluster_names_vec != "All Occupations")]

# Create empty list to hold all the ggplots to be created
empty_list <- vector("list", length(cluster_names_vec))
names(empty_list) <- cluster_names_vec
all_ggplots_list <- list(edu        = empty_list,
                         job_growth = empty_list,
                         wages      = empty_list
                         )
```


```{r make education plots, warning=FALSE}
my_colors <- c("#00264D","#405C7A", "#8C9DAF","#CCD4DB")
#c("#003366", "#335C85", "#6685A3", "#99ADC2") 
#c("#003366", "#2E5882", "#7490AC", "#C4D0DC")
nonduplicated_prepped$predominant_education_level <- fct_relevel(nonduplicated_prepped$predominant_education_level,"Graduate / Professional Degree","Bachelor's Degree","Some College / Associate Degree","High School Diploma")

names(my_colors) <- levels(nonduplicated_prepped$predominant_education_level)[1:4]
#names(my_colors) <- c("Graduate / Professional Degree","Bachelor's Degree","Some College / Associate Degree","High School Diploma")

nonduplicated_prepped %>% 
  mutate(pathway_for_labels = str_replace_all(pathway,"Transportation Systems/Infrastructure Planning, Management, and Regulation", "Transportation Systems Management")) %>% 
  mutate(pathway_for_labels = str_replace_all(pathway, "Tele", "Tele-\n")) %>% 
  mutate(pathway_for_labels = str_replace_all(pathway, " ", "\n")) %>% 
  mutate(pathway_for_labels = str_replace_all(pathway_for_labels, "/", "/\n"))  -> nonduplicated


for (clust in cluster_names_vec){
  
  edu_plot <- nonduplicated %>% 
                 filter(cluster == clust, !is.na(predominant_education_level)) %>% 
     ggplot(aes(pathway_for_labels, fill = predominant_education_level)) + 
     geom_bar(position = "fill",width=0.8) + 
     theme(panel.grid = element_blank(),
        axis.title = element_blank(),
        legend.title = element_blank(),
        legend.text = element_text(size=13,color = "black"),
        axis.text.x = element_text(size=13,color = "black"), 
        axis.text.y = element_text(size=13,color = "black"), 
        panel.background = element_blank(), 
        axis.line.x = element_line(color = "grey"), 
        axis.line.y = element_line(color = "grey"))+
    scale_y_continuous(expand = expansion(mult = c(0, .1)), 
                       labels = scales::percent_format(accuracy = 1), 
                       breaks = seq(0,1, 0.1)) +
    scale_x_discrete(expand=c(0.001, 0))+
    scale_fill_manual(values  = my_colors) +
    scale_color_manual(values = my_colors)
  
  all_ggplots_list$edu[[which(cluster_names_vec == clust)]] <- edu_plot  # Save plot into the list of all ggplots
  
  cluster_3ltr <- strtrim(clust,3)
  
  ggsave(here::here("images", paste0(cluster_3ltr,"-fig1.png")), height = 2.5, width = 7.5, units = c("in"))
}

print(all_ggplots_list$edu)
```


```{r setup styling for job growth plots}
##Horizontal Bars
my_colors2 <- c("darkgrey", "#405C7A")
jobs_labels <- c("2018 Estimate", "2028 Projection")
text_size      <- 5
text_width     <- 0.8
text_vertical  <- 0
text_height    <- -0.05

nonduplicated %>% 
  mutate(pathway = str_replace_all(pathway,"Transportation Systems/Infrastructure Planning, Management, and Regulation", "Transportation Systems Management")) %>% 
  mutate(pathway_for_labels_change = paste(pathway,"\n", "(", trimws(format(round(fraction_change_jobs*100, digits = 1), nsmall = 1)), "%", ")", sep = "")) -> nonduplicated 

my_theme <- theme(legend.title = element_blank(),
                  axis.title.y = element_blank(),
                  panel.grid.minor.y = element_blank(),
                  panel.grid.major.y = element_blank(),
                  axis.text = element_text(color = "black"), 
                  panel.background = element_blank(), 
                  panel.grid.major.x = element_blank(), 
                  panel.grid.minor.x = element_blank(),
                  axis.ticks = element_blank(), 
                  axis.text.x = element_text(),
                  text=element_text(size=17))
```


```{r make one job growth plot, eval=FALSE}
# for (clust in cluster_names_vec){
clust <- cluster_names_vec[4]

nonduplicated %>%
  filter(!is.na(pathway), is.na(soc_title), cluster == clust) %>%
  select(pathway_for_labels_change, num_jobs_estimate, num_jobs_projected) -> linked_pathway

linked_pathway <- melt(linked_pathway, id = "pathway_for_labels_change")

# exp_limit_stretch_factor <- 1.1
# exp_limit <- max(linked_pathway$value)*exp_limit_stretch_factor

job_growth_plot <- ggplot(linked_pathway, aes(value, pathway_for_labels_change, fill = variable)) +
  geom_bar(stat="identity", position =  position_dodge2(reverse=TRUE)) +
  xlab("Number of Jobs") +
  my_theme +
  scale_fill_manual(values = my_colors2,
                    labels = jobs_labels) +
  scale_x_continuous(labels = c("0", "", "", ""), 
                     expand = expansion(mult = c(0, .1)),
                     limits = c(NA,NA)) +
  scale_y_discrete(expand = expansion(mult = c(0, .1))) +
  geom_text(aes(label = formatC(value, big.mark = ",", format = "f", drop0trailing = TRUE)), 
            size     = 5, 
            position = position_dodge2(width = text_width, reverse=TRUE), 
            vjust    = text_vertical, 
            hjust    = text_height) #+
  # expand_limits(x = exp_limit)

  # cluster_3ltr <- strtrim(clust,3)
#  ggsave(here::here("images", paste0(cluster_3ltr,"-fig2.png")), height = 2.5, width = 7.5, units = c("in"))
  print(job_growth_plot)
  print(linked_pathway)
# }
```

```{r make job growth plot, eval=FALSE}
# Business Management and Administration

clust <- cluster_names_vec[4]

linked_pathway <- nonduplicated %>%
  filter(!is.na(pathway), is.na(soc_title),cluster == clust) %>%
  select(pathway_for_labels_change, num_jobs_estimate, num_jobs_projected)

linked_pathway <- melt(linked_pathway, id = "pathway_for_labels_change")

exp_limit_stretch_factor <- 1.1
exp_limit <- max(linked_pathway$value)*exp_limit_stretch_factor

ggplot(linked_pathway, aes(value, pathway_for_labels_change, fill =variable)) +
  geom_bar(stat="identity", position =  position_dodge2(reverse=TRUE)) +
  xlab("Number of Jobs") +
  my_theme +
  scale_fill_manual(values = my_colors2,
                    labels = jobs_labels) +
  scale_x_continuous(labels = c("0", "", "", "",""), expand = expansion(mult = c(0, .1))) +
  scale_y_discrete(expand = expansion(mult = c(0, .1))) +
  geom_text(aes(label = formatC(value, big.mark = ",", format = "f", drop0trailing = TRUE)), 
            size = text_size, 
            position =  position_dodge2(width = text_width, reverse=TRUE), 
            vjust = text_vertical, 
            hjust = text_height) + 
  expand_limits(x = exp_limit) 

```



```{r make job growth plots Ag}
## Agriculture 

clust <- "Agriculture, Food, and Natural Resources"

nonduplicated %>%
  filter(!is.na(pathway), is.na(soc_title), cluster == clust) %>%
  select(pathway_for_labels_change, num_jobs_estimate, num_jobs_projected) -> ag_linked_pathway

ag_linked_pathway <- melt(ag_linked_pathway, id = "pathway_for_labels_change")

ggplot(ag_linked_pathway, aes(value, pathway_for_labels_change, fill =variable)) +
  geom_bar(stat="identity", position =  position_dodge2(reverse=TRUE)) +
  xlab("Number of Jobs") +
  my_theme +
  scale_fill_manual(values = my_colors2,
                    labels = jobs_labels) +
  scale_x_continuous(labels = c("0", "", "", "", ""), expand = expansion(mult = c(0, .1))) +
  scale_y_discrete(expand = expansion(mult = c(0, .1))) +
  geom_text(aes(label = formatC(value, big.mark = ",", format = "f", drop0trailing = TRUE)), 
            size = text_size, 
            position =  position_dodge2(width = text_width, reverse=TRUE), 
            vjust = text_vertical, 
            hjust = text_height) +
  expand_limits(x = 35000) -> job_growth_plot

all_ggplots_list$job_growth[[which(cluster_names_vec == clust)]] <- job_growth_plot  # Save plot into the list of all ggplots

ggsave(here::here("images","Agr-fig2.png"), height = 2.5, width = 7.5, units = c("in"))
```


```{r make job growth plots Arch}
# Architecture and Construction

clust <- "Architecture and Construction"

arch_linked_pathway <- nonduplicated %>%
  filter(!is.na(pathway), is.na(soc_title), cluster == "Architecture and Construction") %>%
  select(pathway_for_labels_change, num_jobs_estimate, num_jobs_projected)

arch_linked_pathway <- melt(arch_linked_pathway, id = "pathway_for_labels_change")

ggplot(arch_linked_pathway, aes(value, pathway_for_labels_change, fill =variable)) +
  geom_bar(stat="identity", position =  position_dodge2(reverse=TRUE)) +
  xlab("Number of Jobs") +
  my_theme +
  scale_fill_manual(values = my_colors2,
                    labels = jobs_labels) +
  scale_x_continuous(labels = c("0", "", "", "", ""), expand = expansion(mult = c(0, .1))) +
  scale_y_discrete(expand = expansion(mult = c(0, .1))) +
  geom_text(aes(label = formatC(value, big.mark = ",", format = "f", drop0trailing = TRUE)), 
            size = text_size, 
            position =  position_dodge2(width = text_width, reverse=TRUE), 
            vjust = text_vertical, 
            hjust = text_height) + 
  expand_limits(x = 205000) -> job_growth_plot

all_ggplots_list$job_growth[[which(cluster_names_vec == clust)]] <- job_growth_plot  # Save plot into the list of all ggplots

  ggsave(here::here("images","Arc-fig2.png"), height = 2.5, width = 7.5, units = c("in"))
```


```{r make job growth plots}
# Arts, Audio/Video Technology, and Communications

clust <- "Arts, Audio/Video Technology, and Communications"

arts_linked_pathway <- nonduplicated %>%
  filter(!is.na(pathway), is.na(soc_title), cluster == "Arts, Audio/Video Technology, and Communications") %>%
  select(pathway_for_labels_change, num_jobs_estimate, num_jobs_projected)
arts_linked_pathway <- melt(arts_linked_pathway, id = "pathway_for_labels_change")

ggplot(arts_linked_pathway, aes(value, pathway_for_labels_change, fill =variable)) +
  geom_bar(stat="identity", position =  position_dodge2(reverse=TRUE)) +
  xlab("Number of Jobs") +
  my_theme +
  scale_fill_manual(values = my_colors2,
                    labels = jobs_labels) +
  scale_x_continuous(labels = c("0", "", "", "", ""), expand = expansion(mult = c(0, .1))) +
  scale_y_discrete(expand = expansion(mult = c(0, .1))) +
  geom_text(aes(label = formatC(value, big.mark = ",", format = "f", drop0trailing = TRUE)), 
            size = text_size, 
            position =  position_dodge2(width = text_width, reverse=TRUE), 
            vjust = text_vertical, 
            hjust = text_height) +
  expand_limits(x = 18000) -> job_growth_plot

all_ggplots_list$job_growth[[which(cluster_names_vec == clust)]] <- job_growth_plot  # Save plot into the list of all ggplots


ggsave(here::here("images","Art-fig2.png"), height = 2.5, width = 7.5, units = c("in"))
```


```{r make job growth plots Biz Admin}
# Business Management and Administration

clust <- "Business Management and Administration"

business_linked_pathway <- nonduplicated %>%
  filter(!is.na(pathway), is.na(soc_title),cluster == "Business Management and Administration") %>%
  select(pathway_for_labels_change, num_jobs_estimate, num_jobs_projected)
business_linked_pathway <- melt(business_linked_pathway, id = "pathway_for_labels_change")

ggplot(business_linked_pathway, aes(value, pathway_for_labels_change, fill =variable)) +
  geom_bar(stat="identity", position =  position_dodge2(reverse=TRUE)) +
  xlab("Number of Jobs") +
  my_theme +
  scale_fill_manual(values = my_colors2,
                    labels = jobs_labels) +
  scale_x_continuous(labels = c("0", "", "", "", ""), expand = expansion(mult = c(0, .1))) +
  scale_y_discrete(expand = expansion(mult = c(0, .1))) +
  geom_text(aes(label = formatC(value, big.mark = ",", format = "f", drop0trailing = TRUE)), 
            size = text_size, 
            position =  position_dodge2(width = text_width, reverse=TRUE), 
            vjust = text_vertical, 
            hjust = text_height) + 
  expand_limits(x = 340000) -> job_growth_plot

all_ggplots_list$job_growth[[which(cluster_names_vec == clust)]] <- job_growth_plot  # Save plot into the list of all ggplots
 

ggsave(here::here("images","Bus-fig2.png"), height = 2.5, width = 7.5, units = c("in"))
```


```{r make some more job growth plots}
# Education and Training

clust <- "Education and Training"

edu_linked_pathway <- nonduplicated %>%
  filter(!is.na(pathway), is.na(soc_title),cluster == "Education and Training") %>%
  select(pathway_for_labels_change, num_jobs_estimate, num_jobs_projected)
edu_linked_pathway <- melt(edu_linked_pathway, id = "pathway_for_labels_change")

ggplot(edu_linked_pathway, aes(value, pathway_for_labels_change, fill =variable)) +
  geom_bar(stat="identity", position =  position_dodge2(reverse=TRUE)) +
  xlab("Number of Jobs") +
  my_theme +
  scale_fill_manual(values = my_colors2,
                    labels = jobs_labels) +
  scale_x_continuous(labels = c("0", "", "", "", ""), expand = expansion(mult = c(0, .1))) +
  scale_y_discrete(expand = expansion(mult = c(0, .1))) +
  geom_text(aes(label = formatC(value, big.mark = ",", format = "f", drop0trailing = TRUE)), 
            size = text_size, 
            position =  position_dodge2(width = text_width, reverse=TRUE), 
            vjust = text_vertical, 
            hjust = text_height) +
  expand_limits(x = 205000) -> job_growth_plot

all_ggplots_list$job_growth[[which(cluster_names_vec == clust)]] <- job_growth_plot  # Save plot into the list of all ggplots
 

  ggsave(here::here("images","Edu-fig2.png"), height = 2.5, width = 7.5, units = c("in"))

# Finance

clust <- "Finance"

finance_linked_pathway <- nonduplicated %>%
  filter(!is.na(pathway),is.na(soc_title), cluster == "Finance") %>%
  select(pathway_for_labels_change, num_jobs_estimate, num_jobs_projected)
finance_linked_pathway <- melt(finance_linked_pathway, id = "pathway_for_labels_change")

ggplot(finance_linked_pathway, aes(value, pathway_for_labels_change, fill =variable)) +
  geom_bar(stat="identity", position =  position_dodge2(reverse=TRUE)) +
  xlab("Number of Jobs") +
  my_theme +
  scale_fill_manual(values = my_colors2,
                    labels = jobs_labels) +
  scale_x_continuous(labels = c("0", "", "", "", ""), expand = expansion(mult = c(0, .1))) +
  scale_y_discrete(expand = expansion(mult = c(0, .1))) +
  geom_text(aes(label = formatC(value, big.mark = ",", format = "f", drop0trailing = TRUE)), 
            size = text_size, 
            position =  position_dodge2(width = text_width, reverse=TRUE), 
            vjust = text_vertical, 
            hjust = text_height) + 
  expand_limits(x = 110000) -> job_growth_plot

all_ggplots_list$job_growth[[which(cluster_names_vec == clust)]] <- job_growth_plot  # Save plot into the list of all ggplots
 
ggsave(here::here("images","Fin-fig2.png"), height = 2.5, width = 7.5, units = c("in"))
```


```{r make job growth plot for Government cluster}
# Government and Public Administration

clust <- "Government and Public Administration"

gov_linked_pathway <- nonduplicated %>%
  filter(!is.na(pathway),is.na(soc_title), !is.na(num_jobs_estimate), cluster == clust) %>%
  select(pathway_for_labels_change, num_jobs_estimate, num_jobs_projected)

gov_linked_pathway <- melt(gov_linked_pathway, id = "pathway_for_labels_change")

ggplot(gov_linked_pathway, aes(value, pathway_for_labels_change, fill =variable)) +
  geom_bar(stat="identity", position =  position_dodge2(reverse=TRUE)) +
  xlab("Number of Jobs") +
  my_theme +
  scale_fill_manual(values = my_colors2,
                    labels = jobs_labels) +
  scale_x_continuous(labels = c("0", "", "", "", "", ""), expand = expansion(mult = c(0, .1))) +
  scale_y_discrete(expand = expansion(mult = c(0, .1))) +
  geom_text(aes(label = formatC(value, big.mark = ",", format = "f", drop0trailing = TRUE)),
            size = text_size,
            position =  position_dodge2(width = text_width, reverse=TRUE),
            vjust = text_vertical,
            hjust = text_height) +
  expand_limits(x = 22000) -> job_growth_plot

all_ggplots_list$job_growth[[which(cluster_names_vec == clust)]] <- job_growth_plot  # Save plot into the list of all ggplots

  ggsave(here::here("images","Gov-fig2.png"), height = 2.5, width = 7.5, units = c("in"))
```


```{r make yet more job growth plots}
# Health Science

clust <- "Health Science"

health_linked_pathway <- nonduplicated %>%
  filter(!is.na(pathway),is.na(soc_title), cluster == "Health Science") %>%
  select(pathway_for_labels_change, num_jobs_estimate, num_jobs_projected)
health_linked_pathway <- melt(health_linked_pathway, id = "pathway_for_labels_change")

ggplot(health_linked_pathway, aes(value, pathway_for_labels_change, fill =variable)) +
  geom_bar(stat="identity", position =  position_dodge2(reverse=TRUE)) +
  xlab("Number of Jobs") +
  my_theme +
  scale_fill_manual(values = my_colors2,
                    labels = jobs_labels) +
  scale_x_continuous(labels = c("0", "", "", ""), expand = expansion(mult = c(0, .1))) +
  scale_y_discrete(expand = expansion(mult = c(0, .1))) +
  geom_text(aes(label = formatC(value, big.mark = ",", format = "f", drop0trailing = TRUE)), 
            size = text_size, 
            position =  position_dodge2(width = text_width, reverse=TRUE), 
            vjust = text_vertical, 
            hjust = text_height) + 
  expand_limits(x = 310000) -> job_growth_plot

all_ggplots_list$job_growth[[which(cluster_names_vec == clust)]] <- job_growth_plot  # Save plot into the list of all ggplots
 
 
  ggsave(here::here("images","Hea-fig2.png"), height = 2.5, width = 7.5, units = c("in"))

 # Hospitality and Tourism

clust <- "Hospitality and Tourism"

hosp_linked_pathway <- nonduplicated %>%
  filter(!is.na(pathway),is.na(soc_title), !is.na(num_jobs_estimate), cluster == "Hospitality and Tourism") %>%
  select(pathway_for_labels_change, num_jobs_estimate, num_jobs_projected)
hosp_linked_pathway <- melt(hosp_linked_pathway, id = "pathway_for_labels_change")

ggplot(hosp_linked_pathway, aes(value, pathway_for_labels_change, fill =variable)) +
  geom_bar(stat="identity", position =  position_dodge2(reverse=TRUE)) +
  xlab("Number of Jobs") +
  my_theme +
  scale_fill_manual(values = my_colors2,
                    labels = jobs_labels) +
  scale_x_continuous(labels = c("0", "", "", "", ""), expand = expansion(mult = c(0, .1))) +
  scale_y_discrete(expand = expansion(mult = c(0, .1))) +
  geom_text(aes(label = formatC(value, big.mark = ",", format = "f", drop0trailing = TRUE)), 
            size = text_size, 
            position =  position_dodge2(width = text_width, reverse=TRUE), 
            vjust = text_vertical, 
            hjust = text_height) + 
  expand_limits(x = 405000) -> job_growth_plot

all_ggplots_list$job_growth[[which(cluster_names_vec == clust)]] <- job_growth_plot  # Save plot into the list of all ggplots
 

  ggsave(here::here("images","Hos-fig2.png"), height = 2.5, width = 7.5, units = c("in"))

# Human Services

clust <- "Human Services"

humanserv_linked_pathway <- nonduplicated %>%
  filter(!is.na(pathway), is.na(soc_title), !is.na(num_jobs_estimate), cluster == "Human Services") %>%
  select(pathway_for_labels_change, num_jobs_estimate, num_jobs_projected)
humanserv_linked_pathway <- melt(humanserv_linked_pathway, id = "pathway_for_labels_change")

ggplot(humanserv_linked_pathway, aes(value, pathway_for_labels_change, fill =variable)) +
  geom_bar(stat="identity", position =  position_dodge2(reverse=TRUE)) +
  xlab("Number of Jobs") +
  my_theme +
  scale_fill_manual(values = my_colors2,
                    labels = jobs_labels) +
  scale_x_continuous(labels = c("0", "", "", "", ""), expand = expansion(mult = c(0, .1))) +
  scale_y_discrete(expand = expansion(mult = c(0, .1))) +
  geom_text(aes(label = formatC(value, big.mark = ",", format = "f", drop0trailing = TRUE)), 
            size = text_size, 
            position =  position_dodge2(width = text_width, reverse=TRUE), 
            vjust = text_vertical, 
            hjust = text_height) + 
  expand_limits(x = 145000) -> job_growth_plot

all_ggplots_list$job_growth[[which(cluster_names_vec == clust)]] <- job_growth_plot  # Save plot into the list of all ggplots
 

  ggsave(here::here("images","Hum-fig2.png"), height = 2.5, width = 7.5, units = c("in"))

# Information Technology

clust <- "Information Technology"

it_linked_pathway <- nonduplicated %>%
  filter(!is.na(pathway), is.na(soc_title), !is.na(num_jobs_estimate), cluster == "Information Technology") %>%
  select(pathway_for_labels_change, num_jobs_estimate, num_jobs_projected)
it_linked_pathway <- melt(it_linked_pathway, id = "pathway_for_labels_change")

ggplot(it_linked_pathway, aes(value, pathway_for_labels_change, fill =variable)) +
  geom_bar(stat="identity", position =  position_dodge2(reverse=TRUE)) +
  xlab("Number of Jobs") +
  my_theme +
  scale_fill_manual(values = my_colors2,
                    labels = jobs_labels) +
  scale_x_continuous(labels = c("0", "", "", "", ""), expand = expansion(mult = c(0, .1))) +
  scale_y_discrete(expand = expansion(mult = c(0, .1))) +
  geom_text(aes(label = formatC(value, big.mark = ",", format = "f", drop0trailing = TRUE)), 
            size = text_size, 
            position =  position_dodge2(width = text_width, reverse=TRUE), 
            vjust = text_vertical, 
            hjust = text_height) + 
  expand_limits(x = 150000) -> job_growth_plot

all_ggplots_list$job_growth[[which(cluster_names_vec == clust)]] <- job_growth_plot  # Save plot into the list of all ggplots
 

  ggsave(here::here("images","Inf-fig2.png"), height = 2.5, width = 7.5, units = c("in"))

# Law, Public Safety, Corrections, and Security

clust <- "Law, Public Safety, Corrections, and Security"

law_linked_pathway <- nonduplicated %>%
  filter(!is.na(pathway),is.na(soc_title), !is.na(num_jobs_estimate), cluster == "Law, Public Safety, Corrections, and Security") %>%
  select(pathway_for_labels_change, num_jobs_estimate, num_jobs_projected)
law_linked_pathway <- melt(law_linked_pathway, id = "pathway_for_labels_change")

ggplot(law_linked_pathway, aes(value, pathway_for_labels_change, fill =variable)) +
  geom_bar(stat="identity", position =  position_dodge2(reverse=TRUE)) +
  xlab("Number of Jobs") +
  my_theme +
  scale_fill_manual(values = my_colors2,
                    labels = jobs_labels) +
  scale_x_continuous(labels = c("0", "", "", "", "", ""), expand = expansion(mult = c(0, .1))) +
  scale_y_discrete(expand = expansion(mult = c(0, .1))) +
  geom_text(aes(label = formatC(value, big.mark = ",", format = "f", drop0trailing = TRUE)), 
            size = text_size, 
            position =  position_dodge2(width = text_width, reverse=TRUE), 
            vjust = text_vertical, 
            hjust = text_height) + 
  expand_limits(x = 47000) -> job_growth_plot

all_ggplots_list$job_growth[[which(cluster_names_vec == clust)]] <- job_growth_plot  # Save plot into the list of all ggplots
 
 
  ggsave(here::here("images","Law-fig2.png"), height = 2.5, width = 7.5, units = c("in"))

# Manufacturing
 
clust <- "Manufacturing"

manufacturing_linked_pathway <- nonduplicated %>%
  filter(!is.na(pathway),is.na(soc_title), !is.na(num_jobs_estimate), cluster == "Manufacturing") %>%
  select(pathway_for_labels_change, num_jobs_estimate, num_jobs_projected)
manufacturing_linked_pathway <- melt(manufacturing_linked_pathway, id = "pathway_for_labels_change")

ggplot(manufacturing_linked_pathway, aes(value, pathway_for_labels_change, fill =variable)) +
  geom_bar(stat="identity", position =  position_dodge2(reverse=TRUE)) +
  xlab("Number of Jobs") +
  my_theme +
  scale_fill_manual(values = my_colors2,
                    labels = jobs_labels) +
  scale_x_continuous(labels = c("0", "", "", "", ""), expand = expansion(mult = c(0, .1))) +
  scale_y_discrete(expand = expansion(mult = c(0, .1))) +
  geom_text(aes(label = formatC(value, big.mark = ",", format = "f", drop0trailing = TRUE)), 
            size = text_size, 
            position =  position_dodge2(width = text_width, reverse=TRUE), 
            vjust = text_vertical, 
            hjust = text_height) + 
  expand_limits(x = 105000) -> job_growth_plot

all_ggplots_list$job_growth[[which(cluster_names_vec == clust)]] <- job_growth_plot  # Save plot into the list of all ggplots
 

  ggsave(here::here("images","Man-fig2.png"), height = 2.5, width = 7.5, units = c("in"))

# Marketing

clust <- "Marketing"

marketing_linked_pathway <- nonduplicated %>%
  filter(!is.na(pathway),is.na(soc_title), !is.na(num_jobs_estimate), !is.na(num_jobs_projected), cluster == "Marketing") %>%
  select(pathway_for_labels_change, num_jobs_estimate, num_jobs_projected)
marketing_linked_pathway <- melt(marketing_linked_pathway, id = "pathway_for_labels_change")

ggplot(marketing_linked_pathway, aes(value, pathway_for_labels_change, fill =variable)) +
  geom_bar(stat="identity", position =  position_dodge2(reverse=TRUE)) +
  xlab("Number of Jobs") +
  my_theme +
  scale_fill_manual(values = my_colors2,
                    labels = jobs_labels) +
  scale_x_continuous(labels = c("0", "", "", "", "", ""), expand = expansion(mult = c(0, .1))) +
  scale_y_discrete(expand = expansion(mult = c(0, .1))) +
  geom_text(aes(label = formatC(value, big.mark = ",", format = "f", drop0trailing = TRUE)), 
            size = text_size, 
            position =  position_dodge2(width = text_width, reverse=TRUE), 
            vjust = text_vertical, 
            hjust = text_height) + 
  expand_limits(x = 470000) -> job_growth_plot

all_ggplots_list$job_growth[[which(cluster_names_vec == clust)]] <- job_growth_plot  # Save plot into the list of all ggplots
 

  ggsave(here::here("images","Mar-fig2.png"), height = 2.5, width = 7.5, units = c("in"))

# Science, Technology, Engineering, and Mathematics

clust <- "Science, Technology, Engineering, and Mathematics"

stem_linked_pathway <- nonduplicated %>%
  filter(!is.na(pathway), is.na(soc_title), !is.na(num_jobs_estimate), !is.na(num_jobs_projected), cluster == "Science, Technology, Engineering, and Mathematics") %>%
  select(pathway_for_labels_change, num_jobs_estimate, num_jobs_projected)
stem_linked_pathway <- melt(stem_linked_pathway, id = "pathway_for_labels_change")

ggplot(stem_linked_pathway, aes(value, pathway_for_labels_change, fill =variable)) +
  geom_bar(stat="identity", position =  position_dodge2(reverse=TRUE)) +
  xlab("Number of Jobs") +
  my_theme +
  scale_fill_manual(values = my_colors2,
                    labels = jobs_labels) +
  scale_x_continuous(labels = c("0", "", "", "", "", ""), expand = expansion(mult = c(0, .1))) +
  scale_y_discrete(expand = expansion(mult = c(0, .1))) +
  geom_text(aes(label = formatC(value, big.mark = ",", format = "f", drop0trailing = TRUE)), 
            size = text_size, 
            position =  position_dodge2(width = text_width, reverse=TRUE), 
            vjust = text_vertical, 
            hjust = text_height) -> job_growth_plot

all_ggplots_list$job_growth[[which(cluster_names_vec == clust)]] <- job_growth_plot  # Save plot into the list of all ggplots
 
  
  ggsave(here::here("images","Sci-fig2.png"), height = 2.5, width = 7.5, units = c("in"))

# Transportation, Distribution, and Logistics

clust <- "Transportation, Distribution, and Logistics"

transport_linked_pathway <- nonduplicated %>%
  filter(!is.na(pathway), is.na(soc_title), !is.na(num_jobs_estimate), !is.na(num_jobs_projected), cluster == "Transportation, Distribution, and Logistics") %>%
  select(pathway_for_labels_change, num_jobs_estimate, num_jobs_projected)
transport_linked_pathway <- melt(transport_linked_pathway, id = "pathway_for_labels_change")

ggplot(transport_linked_pathway, aes(value, pathway_for_labels_change, fill =variable)) +
  geom_bar(stat="identity", position =  position_dodge2(reverse=TRUE)) +
  xlab("Number of Jobs") +
  my_theme +
  scale_fill_manual(values = my_colors2,
                    labels = jobs_labels) +
  scale_x_continuous(labels = c("0", "", "", "", ""), expand = expansion(mult = c(0, .1))) +
  scale_y_discrete(expand = expansion(mult = c(0, .1))) +
  geom_text(aes(label = formatC(value, big.mark = ",", format = "f", drop0trailing = TRUE)), 
            size = text_size, 
            position =  position_dodge2(width = text_width, reverse=TRUE), 
            vjust = text_vertical, 
            hjust = text_height) + 
  expand_limits(x = 160000) -> job_growth_plot

all_ggplots_list$job_growth[[which(cluster_names_vec == clust)]] <- job_growth_plot  # Save plot into the list of all ggplots
 
 
  ggsave(here::here("images","Tra-fig2.png"), height = 2.5, width = 7.5, units = c("in"))

# Energy

clust <- "Energy"

energy_linked_pathway <- nonduplicated %>%
  filter(!is.na(pathway), is.na(soc_title), !is.na(num_jobs_estimate), !is.na(num_jobs_projected), cluster == "Energy") %>%
  select(pathway_for_labels_change, num_jobs_estimate, num_jobs_projected)
energy_linked_pathway <- melt(energy_linked_pathway, id = "pathway_for_labels_change")

ggplot(energy_linked_pathway, aes(value, pathway_for_labels_change, fill = variable)) +
  geom_bar(stat="identity", position =  position_dodge2(reverse=TRUE)) +
  xlab("Number of Jobs") +
  my_theme +
  scale_fill_manual(values = my_colors2,
                    labels = jobs_labels) +
  scale_x_continuous(labels = c("0", "", "", "", ""), expand = expansion(mult = c(0, .1))) +
  scale_y_discrete(expand = expansion(mult = c(0, .1))) +
  geom_text(aes(label = formatC(value, big.mark = ",", format = "f", drop0trailing = TRUE)), 
            size = text_size, 
            position =  position_dodge2(width = text_width, reverse=TRUE), 
            vjust = text_vertical, 
            hjust = text_height) + 
  expand_limits(x = 7000) -> job_growth_plot

all_ggplots_list$job_growth[[which(cluster_names_vec == clust)]] <- job_growth_plot  # Save plot into the list of all ggplots
 
 
  ggsave(here::here("images","Ene-fig2.png"), height = 2.5, width = 7.5, units = c("in"))
```

```{r make wage + openings + growth plots, warning = FALSE}

my_colors3 <- c("#1170aa", "#fc7d0d", "#003366", "#5fa2ce", "#c85200", "#a3cce9", "#ffbc79")

for (clustr in cluster_names_vec){
   wages_plot <- nonduplicated %>% filter(cluster == clustr, !is.na(pathway), !is.na(median_income)) %>% 
     ggplot(aes(median_income, pathway, color = pathway)) + 
     geom_point(size = 3) + 
     scale_color_manual(values = my_colors3) + 
     scale_x_continuous(labels = scales::dollar_format()) + 
     xlab("Median Wage of Occupation") + 
     ylab("Pathway") +
     theme(axis.text.x = element_text(color = "black"), 
           axis.text.y = element_text(color = "black"),
           panel.background = element_blank(),
           axis.line = element_line(color = "grey"),
           panel.grid.major.y = element_line(color = "lightgrey"),
           panel.grid.major.x = element_line(color = "lightgrey"),
           axis.title.y = element_blank(),
           text=element_text(size=17)) +
     scale_size_area(max_size = 6) +
     guides(color = FALSE) + labs(size ="Annual Openings") 
   
     all_ggplots_list$wages[[which(cluster_names_vec == clustr)]] <- wages_plot  # Save plot into the list of all ggplots

     # ggsave(paste0(strtrim(clustr,3),"-fig3.png"), path = "images", height = 4.2, width = 7.5, units = c("in"))
}

print(all_ggplots_list$wages)
```


```{r save plots and other objects for later use}

saveRDS(all_ggplots_list,       here::here("dashboard","all_ggplots_list.Rds"))
saveRDS(cluster_names_vec,      here::here("dashboard","cluster_names_vec.Rds"))
saveRDS(nonduplicated_prepped,  here::here("dashboard","nonduplicated_prepped_data.Rds"))
```


```{r confirm that all plots generated correctly}

print(all_ggplots_list)

```
```{r}
print(all_ggplots_list$wages)
```

