---
title: "CTE Trailblazers: Regional Analysis"
author: "Arthur Small"
date:    Version of `r Sys.Date()`
output:  html_notebook
editor_options: 
  chunk_output_type: inline
---
 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r extract table of growing regions for each cluster from full nonduplicated data set, warning = FALSE, message = FALSE, echo=FALSE}
readRDS(here::here("data_prep","nonduplicated-all-regions-and-pathways.Rds")) %>%
  filter(is.na(pathway_code)) %>%
  select(cluster_code, cluster, Region, fraction_change) %>%
  arrange(cluster, desc(fraction_change), Region) -> regional_tbl

regional_tbl %>% 
  group_by(cluster_code) %>%
  filter(fraction_change >= fraction_change[which(Region == "Virginia")]) %>%
  ungroup() %>%
  select(-cluster_code) %>%
  mutate(Projected_Growth_Rate = scales::percent(fraction_change, accuracy = 0.1L)) %>%
  select(Cluster = cluster, Region, Projected_Growth_Rate) -> growing_regions_tbl
```

```{r print table of regional growth rates}
print(growing_regions_tbl)
```
```{r generate LaTeX bullets of fast growing regions by cluster}
cluster_names_vec <- unique(growing_regions_tbl$Cluster, fromLast = TRUE)

growing_regions_tbl %>% 
  mutate(Projected_Growth_Rate = str_replace(Projected_Growth_Rate, "%", "\\\\%")) -> growing_regions_ltx

for(clustr in cluster_names_vec){
  print(clustr)
  
  growing_regions_ltx %>% 
    filter(Cluster == clustr, Region == "Virginia") %>% 
    pull(Projected_Growth_Rate) -> statewide_cluster_growth_rate
  
  writeLines(paste0("are projected to experience occupational growth rates higher than the ",statewide_cluster_growth_rate, " statewide average:"))
  writeLines("    \\begin{itemize}")
  writeLines("    \\setlength\\itemsep{-0.5em}")
  
  growing_regions_ltx %>%
    filter(Cluster == clustr, Region != "Virginia") %>%
    mutate(LaTeX_item = str_c("        \\item \\text{", Region, " (", Projected_Growth_Rate,")" ,"}")) %>%
    pull(LaTeX_item) %>%
    writeLines()
  
  writeLines("    \\end{itemize}\n\n")

}
```

```{r save tibble of regional growth rates, echo=FALSE}
save2file <- here::here("regions", "growing_regions_tbl.Rds")
saveRDS(growing_regions_tbl, save2file)
```

